### PR TITLE
Improve pub.dev PUB POINTS 100->130

### PR DESCRIPTION
**Pull request by mikebosland**
Compare with current https://pub.dev/packages/opentelemetry/score

10 points for lint/deprecation warnings are not addressed.

* Include Apache 2.0 license contents [10pts]
  * https://github.com/dart-lang/pana is looking for a match against one of its licence files for LICENSE. Compare with the LICENSE files in apache licensed projects. https://pub.dev/packages?sort=points
  * The NOTICE file appears to serve the purpose of the old contents of the LICENSE file.
* Note that these are OpenTelementry traces in the description [10pts]
* Add a working example demonstrating tracing including propagation.

## Which problem is this PR solving?

This OpenTelemetry dart implementation provides the tools that needed to get tracing working. When users look at packages on pub.dev a major consideration of package health is pub points. The goal of this PR is to increase the pub points to make this package more desirable for newcomers.

Also, the README.md appears to show non-working options. For example `whichContext` doesn't appear to be valid. A example is supported by the compiler and is executable showing example output.

Fixes # (issue)

## Short description of the change

Change the description, license and add an example to increase pub points to 130/140.

## How Has This Been Tested?

Pub point changes where manually evaluated using:
```sh
$ dart pub global run pana opentelemetry-dart/
```

## Checklist:

- [ ] Unit tests have been added
- [X] Documentation has been updated

### CODE REVIEW

**Comment by aviary2-wf** [comment]
## Security Insights
No security relevant content was detected by automated scans.

## Action Items
* Review PR for [security impact](https://wiki.atl.workiva.net/display/SECURITY/Development+Security+Review+Guidelines); comment "security review required" if needed or unsure
* Verify [`aviary.yaml`](https://wiki.atl.workiva.net/pages/viewpage.action?pageId=42762752#SecurityInsightFramework&Tooling-ConfiguringAviary) coverage of security relevant code
---
_Questions or Comments? Reach out on Slack: #support-infosec._

**Comment by blakeroberts-wk** [comment]
I've reached out to legal on my end about updating the license. I'll get this PR moving after touching base with them.

**Comment by blakeroberts-wk** [comment]
@mikebosland could the following attribution be added to the end of the LICENSE file as well as updated in the NOTICE file?

```
The opentelemetry-dart uses ProtoBuf definitions from the OpenTelemetry Language Protocol (OTLP), a repository with separate copyright
notices and/or license terms. Your use of the source code for the these software repositories is subject to the terms and conditions of the following:

opentelemetry-proto:   https://github.com/open-telemetry/opentelemetry-proto
Licensed under the Apache 2.0 license: https://github.com/open-telemetry/opentelemetry-proto/blob/main/LICENSE 
```

**Comment by mikebosland** [comment]
> @mikebosland could the following attribution be added to the end of the LICENSE file as well as updated in the NOTICE file?
> 
> ```
> The opentelemetry-dart uses ProtoBuf definitions from the OpenTelemetry Language Protocol (OTLP), a repository with separate copyright
> notices and/or license terms. Your use of the source code for the these software repositories is subject to the terms and conditions of the following:
> 
> opentelemetry-proto:   https://github.com/open-telemetry/opentelemetry-proto
> Licensed under the Apache 2.0 license: https://github.com/open-telemetry/opentelemetry-proto/blob/main/LICENSE 
> ```

Adding this text to the LICENSE file causes the license to not be recognised.
`### [x] 0/10 points: Use an OSI-approved license `

This text appears to already be present in the NOTICE.

I am not a lawyer, but the opentelemetry-dart repository doesn't actually contain the opentelemetry-proto repository. Instead, opentelemetry-dart contains this file:
```
$ cat .gitmodules 
[submodule "lib/src/sdk/proto/opentelemetry-proto"]
        path = lib/src/sdk/proto/opentelemetry-proto
        url = git@github.com:open-telemetry/opentelemetry-proto.git
```
I suppose that file is fine under your existing copyright.  The user of opentelemetry-dart needs to take positive action to download opentelemetry-proto. A simple `git clone` doesn't do it.

**Comment by blakeroberts-wk** [comment]
@mikebosland Okay, I've confirmed with folks on my side, we're good to update the attribution in the notice (from otel js to otel proto) and remove the attribution from the license

**Comment by mikebosland** [comment]
Okay, I've made the change (I didn't catch the js vs proto difference!) and synced.

**Review by blakeroberts-wk — APPROVED** [review]

**Comment by blakeroberts-wk** [comment]
QA +1 docs only

**Comment by blakeroberts-wk** [comment]
@Workiva/release-management-p

**Review by changliu-wk — APPROVED** [review]

**Pull request merged**
