### PR TITLE
Fix syntax errors in README example code.

### PR DESCRIPTION
**Pull request by scidev20**
## Which problem is this PR solving?

The code examples in the README file contain syntax errors. Hence, copy&paste does not provide a functional program.

Fixes # (documentation only)

## Short description of the change

Fix code examples in README file.

## How Has This Been Tested?

No test, since it is only Documentation change.

## Checklist:

- [ ] Unit tests have been added
- [x] Documentation has been updated

### CODE REVIEW

**Comment by aviary-wf** [comment]
## Security Insights
No security relevant content was detected by automated scans.

## Action Items
* Review PR for [security impact](https://wiki.atl.workiva.net/display/SECURITY/Development+Security+Review+Guidelines); comment "security review required" if needed or unsure
* Verify [`aviary.yaml`](https://wiki.atl.workiva.net/pages/viewpage.action?pageId=42762752#SecurityInsightFramework&Tooling-ConfiguringAviary) coverage of security relevant code
---
_Questions or Comments? Reach out on Slack: #support-infosec._

**Review by blakeroberts-wk — APPROVED** [review]

**Comment by dustinlessard-wf** [comment]
QA +1 
@Workiva/release-management-p

**Review by dustinlessard-wf — APPROVED** [review]

**Comment by dustinlessard-wf** [comment]
QA +1 
@Workiva/release-management-p

**Comment by colefeisthamel-wf** [comment]
RM +1

**Pull request merged**
