### PR TITLE
Update GHA publishing steps

### PR DESCRIPTION
**Pull request by michaelyeager-wf**
## Which problem is this PR solving?

This PR updates the GHA publish steps to allow publishing this package to be automated.

## Checklist:

- [ ] Unit tests have been added
- [ ] Documentation has been updated

### CODE REVIEW

**Comment by michaelyeager-wf** [comment]
Prior art:

https://github.com/Workiva/json_schema/blob/master/.github/workflows/publish.yaml
https://github.com/Workiva/json_schema/actions/runs/8546854801

Added steps tested working in above repo. We cannot test here without pushing, and cannot do so before merge.

QA +1

**Comment by aviary3-wk** [comment]
## Security Insights
No security relevant content was detected by automated scans.

## Action Items
* Review PR for [security impact](https://wiki.atl.workiva.net/display/SECURITY/Development+Security+Review+Guidelines); comment "security review required" if needed or unsure
* Verify [`aviary.yaml`](https://wiki.atl.workiva.net/pages/viewpage.action?pageId=42762752#SecurityInsightFramework&Tooling-ConfiguringAviary) coverage of security relevant code
---
_Questions or Comments? Reach out on Slack: #support-infosec._

**Review by changliu-wk — APPROVED** [review]

**Review by blakeroberts-wk — APPROVED** [review]

**Comment by michaelyeager-wf** [comment]
@Workiva/release-management-p

**Review by rmconsole-wf — APPROVED** [review]
+1 from RM

**Pull request merged**
