### PR TITLE
O11Y-3733: opentelemetry-dart: Implement Improvements to Timer in BatchSpanProcessor

### PR DESCRIPTION
**Pull request by michaelyeager-wf**
## Which problem is this PR solving?

The implementation of Timer for periodic export of spans from BatchSpanProcessor is convoluted and not as null-safe as it should be.  

This PR simplifies how BatchSpanProcessor uses Timer in emitting spans.

## How Has This Been Tested?

* Confirmed that unit tests pass following these changes.
* Loaded these changes in a small testing application and confirmed that it can be used to properly emit traces.

### CODE REVIEW

**Comment by michaelyeager-wf** [comment]
Loaded these changes in a small testing application and confirmed that it can be used to properly emit traces.

QA +1

**Comment by aviary2-wf** [comment]
## Security Insights
No security relevant content was detected by automated scans.

## Action Items
* Review PR for [security impact](https://wiki.atl.workiva.net/display/SECURITY/Development+Security+Review+Guidelines); comment "security review required" if needed or unsure
* Verify [`aviary.yaml`](https://wiki.atl.workiva.net/pages/viewpage.action?pageId=42762752#SecurityInsightFramework&Tooling-ConfiguringAviary) coverage of security relevant code
---
_Questions or Comments? Reach out on Slack: #support-infosec._

**Review by kennytrytek-wf — APPROVED** [review]
This behavior is in accordance with the spec.
https://github.com/open-telemetry/opentelemetry-specification/blob/main/specification/trace/sdk.md#batching-processor

One thing that is missing is immediate batch export once maximum batch size has been reached, but that was missing before too. It should be added separately.

⛄

**Review by keruitan-wk — APPROVED** [review]

**Review by changliu-wk — APPROVED** [review]

**Review by blakeroberts-wk — APPROVED** [review]

**Comment by michaelyeager-wf** [comment]
@Workiva/release-management-p

**Review by rmconsole-wf — APPROVED** [review]
+1 from RM

**Pull request merged**
