### PR TITLE
O11Y-2150 : Opentelemetry-dart lacks assets helpful to contributors

### PR DESCRIPTION
**Pull request by dustinlessard-wf**
**Problem**
Repo lacks assets helpful to contributors
This repo lacks templates for new issues and a codeowners file

### CODE REVIEW

**Comment by aviary-wf** [comment]
## Security Insights
No security relevant content was detected by automated scans.

## Action Items
* Review PR for [security impact](https://wiki.atl.workiva.net/display/SECURITY/Development+Security+Review+Guidelines); comment "security review required" if needed or unsure
* Verify [`aviary.yaml`](https://wiki.atl.workiva.net/pages/viewpage.action?pageId=42762752#SecurityInsightFramework&Tooling-ConfiguringAviary) coverage of security relevant code
---
_Questions or Comments? Reach out on Slack: #support-infosec._

**Comment by semveraudit-wf** [comment]
### Public API Changes

 No changes to the public API found for commit 4ec9d9a735babb3196495fd634add35e66052309

Showing results for 4ec9d9a735babb3196495fd634add35e66052309
> Powered by [semver-audit-service](https://github.com/Workiva/semver-audit-service). Please report any problems by [filing an issue](https://github.com/Workiva/semver-audit-service/issues).
> Reported by the dart semver audit client 2.2.2
[Browse public API](https://semver-audit.wk-dev.wdesk.org/Workiva/opentelemetry-dart/4ec9d9a735babb3196495fd634add35e66052309).

**Review by blakeroberts-wk — APPROVED** [review]

**Comment by dustinlessard-wf** [comment]
QA+1

**Comment by dustinlessard-wf** [comment]
@Workiva/release-management-p

**Review by rmconsole-wf — APPROVED** [review]
+1 from RM

**Pull request merged**
