### PR TITLE
O11Y-3138: Update deprecation messages

### PR DESCRIPTION
**Pull request by michaelyeager-wf**
## Which problem is this PR solving?

This PR updates deprecation messages to accurately reflect plans for upcoming breaking changes.

## How Has This Been Tested?

* Confirmed passing unit tests following this change.

### CODE REVIEW

**Comment by aviary3-wk** [comment]
## Security Insights
No security relevant content was detected by automated scans.

## Action Items
* Review PR for [security impact](https://wiki.atl.workiva.net/display/SECURITY/Development+Security+Review+Guidelines); comment "security review required" if needed or unsure
* Verify [`aviary.yaml`](https://wiki.atl.workiva.net/pages/viewpage.action?pageId=42762752#SecurityInsightFramework&Tooling-ConfiguringAviary) coverage of security relevant code
---
_Questions or Comments? Reach out on Slack: #support-infosec._

**Comment by semveraudit-wf** [comment]
### Public API Changes

 No changes to the public API found for commit f68fe453ed8cc59fdd1d7b6585e061e8511d457e

Showing results for f68fe453ed8cc59fdd1d7b6585e061e8511d457e
> Powered by [semver-audit-service](https://github.com/Workiva/semver-audit-service). Please report any problems by [filing an issue](https://github.com/Workiva/semver-audit-service/issues).
> Reported by the dart semver audit client 2.2.2
[Browse public API](https://semver-audit.wk-dev.wdesk.org/Workiva/opentelemetry-dart/f68fe453ed8cc59fdd1d7b6585e061e8511d457e).

**Review by keruitan-wk — APPROVED** [review]

**Review by blakeroberts-wk — APPROVED** [review]

**Comment by michaelyeager-wf** [comment]
PR updates deprecation messages.  Confirmed that unit tests pass successfully with this change.  

QA +1

**Comment by michaelyeager-wf** [comment]
@Workiva/release-management-p

**Review by rmconsole-wf — APPROVED** [review]
+1 from RM

**Pull request merged**
