### PR TITLE
O11Y-4632 Release 0.18.3

### PR DESCRIPTION
**Pull request by changliu-wk**
## Which problem is this PR solving?

Release 0.18.3

### CODE REVIEW

**Comment by aviary-wf** [comment]
## Security Insights
No security relevant content was detected by automated scans.

## Action Items
* Review PR for [security impact](https://wiki.atl.workiva.net/display/SECURITY/Development+Security+Review+Guidelines); comment "security review required" if needed or unsure
* Verify [`aviary.yaml`](https://wiki.atl.workiva.net/pages/viewpage.action?pageId=42762752#SecurityInsightFramework&Tooling-ConfiguringAviary) coverage of security relevant code
---
_Questions or Comments? Reach out on Slack: #support-infosec._

**Review by blakeroberts-wk — APPROVED** [review]

**Comment by changliu-wk** [comment]
QA+1

**Comment by changliu-wk** [comment]
@Workiva/release-management-p

**Review by rmconsole-wf — APPROVED** [review]
+1 from RM

**Comment by long1dev** [comment]
I think this should be 0.19.0 because the code shows deprecated members, then in 0.20.0 they should be removed.

**Comment by blakeroberts-wk** [comment]
I'm sorry for breaking your pipeline. I'm not sure it makes sense to bump the minor version for analyzer warnings. I would recommend pinning the patch version of this library or ignoring the lint in a `analysis_options.yaml` file.

**Pull request merged**
