### PR TITLE
O11Y-2792: Update action versions

### PR DESCRIPTION
**Pull request by changliu-wk**
## Which problem is this PR solving?

There is a workflow action failure with all opened PRs, for example: https://github.com/Workiva/opentelemetry-dart/actions/runs/4651289857/jobs/8244311269?pr=104. 

Fixes # (issue)

## Short description of the change

Update the action versions. 

## How Has This Been Tested?

Pass the test workflow. 

## Checklist:

- [ ] Unit tests have been added
- [ ] Documentation has been updated

### CODE REVIEW

**Comment by aviary-wf** [comment]
## Security Insights
No security relevant content was detected by automated scans.

## Action Items
* Review PR for [security impact](https://wiki.atl.workiva.net/display/SECURITY/Development+Security+Review+Guidelines); comment "security review required" if needed or unsure
* Verify [`aviary.yaml`](https://wiki.atl.workiva.net/pages/viewpage.action?pageId=42762752#SecurityInsightFramework&Tooling-ConfiguringAviary) coverage of security relevant code
---
_Questions or Comments? Reach out on Slack: #support-infosec._

**Comment by semveraudit-wf** [comment]
### Public API Changes

 No changes to the public API found for commit fed7de10d059c6cbd74a8fb88fd9175d63bfd93e

Showing results for fed7de10d059c6cbd74a8fb88fd9175d63bfd93e
> Powered by [semver-audit-service](https://github.com/Workiva/semver-audit-service). Please report any problems by [filing an issue](https://github.com/Workiva/semver-audit-service/issues).
> Reported by the dart semver audit client 2.2.2
[Browse public API](https://semver-audit.wk-dev.wdesk.org/Workiva/opentelemetry-dart/fed7de10d059c6cbd74a8fb88fd9175d63bfd93e).

**Review by kennytrytek-wf — APPROVED** [review]
Check succeeded.

QA +1 ⛄

**Comment by changliu-wk** [comment]
QA +1

**Comment by changliu-wk** [comment]
@Workiva/release-management-p

**Review by keruitan-wk — APPROVED** [review]

**Review by rmconsole-wf — APPROVED** [review]
+1 from RM

**Pull request merged**
