### PR TITLE
O11Y-4317: update generated mocks and format project

### PR DESCRIPTION
**Pull request by blakeroberts-wk**
## Which problem is this PR solving?

`make init` (as well as `dart pub publish`) was failing around building the mocks.

```
build_runner:build_runner:
../../../../../.pub-cache/hosted/pub.dev/watcher-1.0.2/lib/src/constructable_file_system_event.dart:7:57: Error: The class 'FileSystemEvent' can't be extended, implemented, or mixed in outside of its library because it's a sealed class.
abstract class _ConstructableFileSystemEvent implements FileSystemEvent {
                                                        ^
```

Fixes # (issue)

## Short description of the change

Update generated mocks from version 5.4.2 to 5.4.4.

## How Has This Been Tested?

Unit tests and whitespace changes only.

## Checklist:

- [ ] Unit tests have been added
- [ ] Documentation has been updated

### CODE REVIEW

**Comment by aviary-wf** [comment]
## Security Insights
No security relevant content was detected by automated scans.

## Action Items
* Review PR for [security impact](https://wiki.atl.workiva.net/display/SECURITY/Development+Security+Review+Guidelines); comment "security review required" if needed or unsure
* Verify [`aviary.yaml`](https://wiki.atl.workiva.net/pages/viewpage.action?pageId=42762752#SecurityInsightFramework&Tooling-ConfiguringAviary) coverage of security relevant code
---
_Questions or Comments? Reach out on Slack: #support-infosec._

**Review by keruitan-wk — APPROVED** [review]

**Comment by blakeroberts-wk** [comment]
QA +1 passing CI is sufficient considering the changes are to tests and whitespace only

**Comment by blakeroberts-wk** [comment]
@Workiva/release-management-p

**Review by rmconsole-wf — APPROVED** [review]
+1 from RM

**Pull request merged**
