### PR TITLE
opentelemetry-dart 0.17.0

### PR DESCRIPTION
**Pull request by michaelyeager-wf**
## Which problem is this PR solving?

This PR combines changes and updates from the following branch PRs:
* #118 
* #123 
* #124 
* #125 
* #128 
* #129

## How Has This Been Tested?

* Confirm that unit tests pass following these changes.
* Loaded these changes in a small testing application and confirmed that it can be used to properly emit traces.

### CODE REVIEW

**Comment by aviary3-wk** [comment]
## Security Insights
<details>
<summary>Error scanning for image validation issues</summary>
</details>

## Action Items
* Review PR for [security impact](https://wiki.atl.workiva.net/display/SECURITY/Development+Security+Review+Guidelines); comment "security review required" if needed or unsure
* Verify [`aviary.yaml`](https://wiki.atl.workiva.net/pages/viewpage.action?pageId=42762752#SecurityInsightFramework&Tooling-ConfiguringAviary) coverage of security relevant code
---
_Questions or Comments? Reach out on Slack: #support-infosec._

**Comment by michaelyeager-wf** [comment]
@aviary-wf

**Review by robbecker-wf — APPROVED** [review]
Each sub-pr has been reviewed. Each one was squashed and merged without conflict. LGTM assuming testing goes well.

**Comment by michaelyeager-wf** [comment]
Loaded these changes in a small testing application.  Confirmed that it can be used to properly emit traces.  Confirmed that context propagates appropriately.

QA +1

**Review by blakeroberts-wk — APPROVED** [review]

**Comment by robbecker-wf** [comment]
@aviary-wf Can you try running again?

**Review by robbecker-wf — DISMISSED** [review]
approving again after removing the Dockerfile

**Comment by michaelyeager-wf** [comment]
Loaded these changes in a small testing application. Confirmed that it can be used to properly emit traces. Confirmed that context propagates appropriately.

QA +1

**Review by blakeroberts-wk — DISMISSED** [review]

**Comment by robbecker-wf** [comment]
@Workiva/release-management-p

**Comment by michaelyeager-wf** [comment]
Loaded these changes in a small testing application. Confirmed that it can be used to properly emit traces. Confirmed that context propagates appropriately.

QA +1

**Review by robbecker-wf — APPROVED** [review]
+10 again

**Review by rmconsole-wf — APPROVED** [review]
+1 from RM

**Pull request merged**
