### PR TITLE
O11Y-3814: version bump

### PR DESCRIPTION
**Pull request by kennytrytek-wf**
Version 0.18.0

### CODE REVIEW

**Comment by aviary2-wf** [comment]
## Security Insights
No security relevant content was detected by automated scans.

## Action Items
* Review PR for [security impact](https://wiki.atl.workiva.net/display/SECURITY/Development+Security+Review+Guidelines); comment "security review required" if needed or unsure
* Verify [`aviary.yaml`](https://wiki.atl.workiva.net/pages/viewpage.action?pageId=42762752#SecurityInsightFramework&Tooling-ConfiguringAviary) coverage of security relevant code
---
_Questions or Comments? Reach out on Slack: #support-infosec._

**Review by blakeroberts-wk — APPROVED** [review]

**Comment by kennytrytek-wf** [comment]
@Workiva/release-management-pp

**Comment by kennytrytek-wf** [comment]
QA +1 ⛄

**Review by rmconsole-wf — APPROVED** [review]
+1 from RM

**Pull request merged**
