### PR TITLE
expose sdk.Attributes

### PR DESCRIPTION
**Pull request by yuzurihaaa**
## Which problem is this PR solving?

Resource is exposed in sdk, but not Attributes for override.

### CODE REVIEW

**Comment by aviary-wf** [comment]
## Security Insights
No security relevant content was detected by automated scans.

## Action Items
* Review PR for [security impact](https://wiki.atl.workiva.net/display/SECURITY/Development+Security+Review+Guidelines); comment "security review required" if needed or unsure
* Verify [`aviary.yaml`](https://wiki.atl.workiva.net/pages/viewpage.action?pageId=42762752#SecurityInsightFramework&Tooling-ConfiguringAviary) coverage of security relevant code
---
_Questions or Comments? Reach out on Slack: #support-infosec._

**Review by blakeroberts-wk — APPROVED** [review]

**Comment by blakeroberts-wk** [comment]
QA +1 ci is sufficient

**Comment by blakeroberts-wk** [comment]
@Workiva/release-management-p

**Comment by dancleereman-wf** [comment]
RM +1

**Pull request merged**
