### PR TITLE
O11Y-4623: Update Context API examples in opentelemetry-dart README

### LINKED ISSUE #162: I can't find `withContext` and `setSpan` from README

### PR DESCRIPTION
**Pull request by michaelyeager-wf**
## Which problem is this PR solving?

This PR updates the README with better context propagation examples following recent API changes.

Fixes #162 

## How Has This Been Tested?

This is a documentation change.  No further testing should be required.

## Checklist:

- [ ] Unit tests have been added
- [x] Documentation has been updated

### CODE REVIEW

**Comment by aviary2-wf** [comment]
## Security Insights
No security relevant content was detected by automated scans.

## Action Items
* Review PR for [security impact](https://wiki.atl.workiva.net/display/SECURITY/Development+Security+Review+Guidelines); comment "security review required" if needed or unsure
* Verify [`aviary.yaml`](https://wiki.atl.workiva.net/pages/viewpage.action?pageId=42762752#SecurityInsightFramework&Tooling-ConfiguringAviary) coverage of security relevant code
---
_Questions or Comments? Reach out on Slack: #support-infosec._

**Comment by michaelyeager-wf** [comment]
@Workiva/release-management-p

**Review by rmconsole-wf — APPROVED** [review]
+1 from RM

**Comment by long1eu** [comment]
Let me get this right. You updated the readme with a deprecated way of doing things?

**Pull request merged**
